version: "3"
services:
  traefik:
    image: "traefik:v2.4.2"
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/opt/letsencrypt/:/letsencrypt/"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command:
      - "--log.level=INFO"
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--ping.entryPoint=websecure"

      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"

      - "--certificatesresolvers.podnoms-cert-resolver.acme.tlschallenge=true"
      # - "--certificatesresolvers.podnoms-cert-resolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.podnoms-cert-resolver.acme.email=fergal.moran@gmail.com"
      - "--certificatesresolvers.podnoms-cert-resolver.acme.storage=/letsencrypt/acme.json"
    labels:
      - "traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.test-redirectscheme.redirectscheme.permanent=true"

  jobs:
    image: "docker.pkg.github.com/podnoms/podnoms-backend/podnoms-jobs"
    container_name: podnoms-jobs
    restart: always
    environment:
      ASPNETCORE_KeyVaultSettings__Vault: ${KeyVaultSettings__Vault}
      ASPNETCORE_KeyVaultSettings__ClientId: ${KeyVaultSettings__ClientId}
      ASPNETCORE_KeyVaultSettings__ClientSecret: ${KeyVaultSettings__ClientSecret}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jobs.rule=Host(`jobs.podnoms.com`)"
      - "traefik.http.routers.jobs.entrypoints=websecure"
      - "traefik.http.routers.jobs.tls.certresolver=podnoms-cert-resolver"

  scraper:
    image: docker.pkg.github.com/podnoms/podnoms-scraper/podnoms-scraper
    container_name: podnoms-scraper
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
      SESSION_SECRET: ${SESSION_SECRET}
      CHROMIUM_BINARY: ${CHROMIUM_BINARY}
      MONGODB_URI: ${MONGODB_URI}
      FACEBOOK_ID: ${FACEBOOK_ID}
      FACEBOOK_SECRET: ${FACEBOOK_SECRET}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.scraper.rule=Host(`scraper.pdnm.be`)"
      - "traefik.http.routers.scraper.entrypoints=websecure"
      - "traefik.http.routers.scraper.tls.certresolver=podnoms-cert-resolver"

  mongo:
    image: mongo
    container_name: podnoms-mongo
    restart: always
    volumes:
      - ./data/dev/mongo:/data/db
    ports:
      - "27017:27017"

networks:
  default:
    external:
      name: jobsnet
